import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

const SYSTEM_PROMPT = `You are a professional document drafting assistant for NICS Estate / AIByteconsult. You specialize in creating legal and business documents related to Bulgaria.

Your task: Generate a professional, well-structured document based on the user's request and provided details.

Document types you can create:
- Power of Attorney (Пълномощно)
- Rental agreements / Lease contracts
- Sale-purchase preliminary contracts
- Business letters and correspondence
- Company registration declarations
- Employment contracts
- Service agreements
- Complaint letters
- Translation requests
- Any other standard legal/business document

Rules:
1. Generate the document in the language the user writes in (or as specified)
2. Use proper legal/business formatting with clear sections
3. Include placeholders like [FULL NAME], [DATE], [ADDRESS] where specific data wasn't provided
4. Add a header and footer appropriate for the document type
5. Be thorough but professional
6. If the user provides their personal details, incorporate them into the document
7. Format the document using markdown with clear headings, numbered sections, and proper structure
8. Always include a note at the end: "This document was generated by AI and should be reviewed by a qualified legal professional before use."`;

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { documentType, userDetails, additionalInfo, language, userEmail } = await req.json();

    if (!documentType) {
      return new Response(
        JSON.stringify({ error: "Document type is required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    if (!userEmail) {
      return new Response(
        JSON.stringify({ error: "Email is required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) throw new Error("LOVABLE_API_KEY is not configured");

    const userPrompt = `Please generate the following document:

**Document Type:** ${documentType}

**User Details:**
${userDetails || "Not provided - use placeholders"}

**Additional Instructions/Information:**
${additionalInfo || "None"}

**Language:** ${language || "Same as the document type description"}

Please generate a complete, professional document ready for review.`;

    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-3-flash-preview",
        messages: [
          { role: "system", content: SYSTEM_PROMPT },
          { role: "user", content: userPrompt },
        ],
        stream: false,
      }),
    });

    if (!response.ok) {
      if (response.status === 429) {
        return new Response(JSON.stringify({ error: "Rate limits exceeded, please try again later." }), {
          status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      if (response.status === 402) {
        return new Response(JSON.stringify({ error: "Service temporarily unavailable." }), {
          status: 402, headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      const t = await response.text();
      console.error("AI gateway error:", response.status, t);
      return new Response(JSON.stringify({ error: "AI service error" }), {
        status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const data = await response.json();
    const generatedContent = data.choices?.[0]?.message?.content || "";

    // Save to database
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    const { error: dbError } = await supabase
      .from("document_generations")
      .insert({
        document_type: documentType,
        user_email: userEmail,
        user_details: userDetails || null,
        additional_info: additionalInfo || null,
        language: language || "en",
        generated_content: generatedContent,
        payment_status: "pending",
      });

    if (dbError) {
      console.error("DB insert error:", dbError);
    }

    // Notify admin about new document generation
    const resendApiKey = Deno.env.get("RESEND_API_KEY");
    if (resendApiKey) {
      try {
        await fetch("https://api.resend.com/emails", {
          method: "POST",
          headers: {
            Authorization: `Bearer ${resendApiKey}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            from: "NICS Estate Docs <noreply@aibyteconsult.com>",
            to: ["info@aibyteconsult.com"],
            subject: `New Document Generation: ${documentType} — ${userEmail}`,
            html: `
              <h2>New Document Generated</h2>
              <p><strong>Document Type:</strong> ${documentType}</p>
              <p><strong>User Email:</strong> ${userEmail}</p>
              <p><strong>Language:</strong> ${language || "en"}</p>
              <p><strong>Payment Status:</strong> Pending</p>
              <hr/>
              <p>Log in to the admin dashboard to review and send the document after payment confirmation.</p>
            `,
          }),
        });
      } catch (emailErr) {
        console.error("Admin notification email error:", emailErr);
      }
    }

    return new Response(
      JSON.stringify({ success: true }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (e) {
    console.error("generate-document error:", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
